[bell]
animation = "EaseOutCirc"
color = "0x660000"
duration = 300

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FFFF00"
text = "#000000"

[colors.primary]
background = "#000000"
foreground = "#dddddd"

[cursor]
thickness = 0.4

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = "Anonymous Pro"

[font.italic]
family = "Anonymous Pro"
style = "Light Italic"

[font.bold]
family = "Anonymous Pro"
style = "Medium"

[font.bold_italic]
family = "Anonymous Pro"
style = "Medium Italic"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "Comma"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = "Period"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u0002"
key = "B"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0006"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000B"
key = "K"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0013"
key = "T"
mods = "Command|Control"

[[keyboard.bindings]]
chars = """
\u001B
"""
key = "J"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018@c;"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\u0000"
key = "Space"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0018@c'"
key = "'"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B-"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u001F"
key = "Minus"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
